version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  redis:
    image: redis:alpine
    container_name: wordpress_redis
    restart: always
    networks:
      - wp_network

  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wordpress_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_REDIS_HOST: redis
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: wordpress_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wp_network
    depends_on:
      - wordpress

volumes:
  db_data:
  wordpress_data:

graphics:
  wp_network: